language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rake spec:models --trace
  - RAILS_ENV=test bundle exec rspec spec/deploy/*_spec.rb --backtrace
before_script:
  - mysql -e 'create database myapp_test'

notifications:
  email:
    recipients:
      - toqoz403@gmail.com
      - bin.honda@gmail.com
      - kenjikaneko0909@yahoo.co.jp
    on_success: change
    on_failure: always
