#!/bin/sh

# description:
#   alias for take coverage when you run rspec.
# example:
#   $ script/cov

set -e

if [ ! $DB ] ; then export DB=sqlite; fi
export COVERAGE=on
export RAILS_ROOT=$(cd "$(dirname $0)"/.. && pwd)

cd $RAILS_ROOT
bundle exec rake spec
