#!/bin/sh

# description:
#   alias for run spec set.
#   /controllers/models/env/deploy
# example:
#   $ script/spec_set

set -e

if [ ! $DB ] ; then export DB=sqlite; fi

# migrate
bundle exec rake db:migrate test

# run spec
bundle exec rake spec:models
bundle exec rake spec:controllers
bundle exec rspec spec/env/*_spec.rb
bundle exec rspec spec/deploy/*_spec.rb
